# Generated by Django 5.1 on 2025-10-31 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("report_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("deepfake_image", "딥페이크 이미지"),
                            ("deepfake_video", "딥페이크 영상"),
                            ("deepfake_audio", "딥페이크 음성"),
                            ("fake_interview", "온라인 면접 딥페이크"),
                        ],
                        max_length=50,
                        verbose_name="신고 유형",
                    ),
                ),
                (
                    "discovery_source",
                    models.CharField(
                        choices=[
                            ("sns", "SNS"),
                            ("messenger", "메신저"),
                            ("website", "웹사이트"),
                            ("email", "이메일"),
                            ("video_conference", "화상회의"),
                            ("other", "기타"),
                        ],
                        max_length=50,
                        verbose_name="발견 경로",
                    ),
                ),
                (
                    "damage_level",
                    models.CharField(
                        choices=[
                            ("personal", "개인 피해"),
                            ("group", "단체 피해"),
                            ("social", "사회적 피해"),
                        ],
                        max_length=20,
                        verbose_name="피해 정도",
                    ),
                ),
                ("description", models.TextField(verbose_name="상세 설명")),
                (
                    "evidence_files",
                    models.JSONField(
                        blank=True,
                        help_text='[{"file_name": "screenshot.png", "file_url": "https://..."}]',
                        null=True,
                        verbose_name="증거 자료",
                    ),
                ),
                (
                    "report_agency",
                    models.CharField(
                        choices=[
                            ("kisa", "한국인터넷진흥원(KISA)"),
                            ("pipc", "개인정보보호위원회"),
                            ("cyberbureau", "사이버수사대"),
                            ("dscc", "디지털성범죄신고센터"),
                            ("moel", "고용노동부"),
                            ("company_hr", "기업 HR 부서"),
                        ],
                        max_length=50,
                        verbose_name="신고 기관",
                    ),
                ),
                (
                    "report_reference_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="신고 접수번호",
                    ),
                ),
                (
                    "report_status",
                    models.CharField(
                        choices=[
                            ("submitted", "접수됨"),
                            ("under_review", "검토 중"),
                            ("in_progress", "처리 중"),
                            ("completed", "완료"),
                            ("rejected", "반려"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="신고 상태",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제출일시"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="detection.analysisrecord",
                        verbose_name="분석 기록",
                    ),
                ),
            ],
            options={
                "verbose_name": "신고",
                "verbose_name_plural": "신고 목록",
                "db_table": "reports",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
