# Generated by Django 5.1 on 2025-10-31 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["user", "-submitted_at"], name="reports_user_id_9b75fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_status"], name="reports_report__0f0178_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_agency"], name="reports_report__245e12_idx"
            ),
        ),
    ]
