# Generated by Django 5.1 on 2025-10-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProtectionJob",
            fields=[
                ("job_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("adversarial_noise", "Adversarial Noise 추가"),
                            ("watermark", "워터마크 삽입"),
                            ("both", "노이즈 + 워터마크"),
                        ],
                        max_length=50,
                        verbose_name="작업 유형",
                    ),
                ),
                (
                    "original_files",
                    models.JSONField(
                        help_text='[{"file_name": "image1.jpg", "file_path": "/path/to/file", "file_size": 1024}]',
                        verbose_name="원본 파일 목록",
                    ),
                ),
                (
                    "protected_files",
                    models.JSONField(
                        blank=True,
                        help_text='[{"file_name": "image1_protected.jpg", "file_path": "/path/to/file", "file_size": 1024}]',
                        null=True,
                        verbose_name="보호된 파일 목록",
                    ),
                ),
                (
                    "job_status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("processing", "처리 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="작업 상태",
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="진행률(%)",
                    ),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="처리 시작 시간"
                    ),
                ),
                (
                    "processing_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="처리 완료 시간"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="오류 메시지"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
            ],
            options={
                "verbose_name": "보호 작업",
                "verbose_name_plural": "보호 작업 목록",
                "db_table": "protection_jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
