# Generated by Django 5.1 on 2025-10-31 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("protection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="protectionjob",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protection_jobs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddIndex(
            model_name="protectionjob",
            index=models.Index(
                fields=["user", "-created_at"], name="protection__user_id_0c1cea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="protectionjob",
            index=models.Index(
                fields=["job_status"], name="protection__job_sta_2c2cc8_idx"
            ),
        ),
    ]
