# Generated by Django 5.1 on 2025-10-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("debug", "DEBUG"),
                            ("info", "INFO"),
                            ("warning", "WARNING"),
                            ("error", "ERROR"),
                            ("critical", "CRITICAL"),
                        ],
                        max_length=20,
                        verbose_name="로그 레벨",
                    ),
                ),
                (
                    "log_category",
                    models.CharField(
                        choices=[
                            ("auth", "인증"),
                            ("api", "API"),
                            ("detection", "탐지"),
                            ("protection", "보호"),
                            ("report", "신고"),
                            ("system", "시스템"),
                            ("database", "데이터베이스"),
                        ],
                        max_length=50,
                        verbose_name="로그 카테고리",
                    ),
                ),
                ("message", models.TextField(verbose_name="메시지")),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="오류 코드"
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(blank=True, null=True, verbose_name="요청 데이터"),
                ),
                (
                    "response_data",
                    models.JSONField(blank=True, null=True, verbose_name="응답 데이터"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
            ],
            options={
                "verbose_name": "시스템 로그",
                "verbose_name_plural": "시스템 로그 목록",
                "db_table": "system_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
