# Generated by Django 5.1 on 2025-10-31 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("detection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoomSession",
            fields=[
                ("session_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "session_name",
                    models.CharField(max_length=255, verbose_name="세션명"),
                ),
                ("start_time", models.DateTimeField(verbose_name="시작 시간")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="종료 시간"
                    ),
                ),
                (
                    "total_captures",
                    models.IntegerField(default=0, verbose_name="총 캡처 수"),
                ),
                (
                    "suspicious_detections",
                    models.IntegerField(default=0, verbose_name="의심 감지 수"),
                ),
                (
                    "session_status",
                    models.CharField(
                        choices=[
                            ("active", "진행 중"),
                            ("completed", "완료"),
                            ("stopped", "중단"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="세션 상태",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zoom_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zoom 세션",
                "verbose_name_plural": "Zoom 세션 목록",
                "db_table": "zoom_sessions",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ZoomCapture",
            fields=[
                ("capture_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("participant_count", models.IntegerField(verbose_name="참가자 수")),
                (
                    "capture_timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="캡처 시간"),
                ),
                (
                    "alert_triggered",
                    models.BooleanField(default=False, verbose_name="경고 발생 여부"),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zoom_captures",
                        to="detection.analysisrecord",
                        verbose_name="분석 기록",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captures",
                        to="zoom.zoomsession",
                        verbose_name="세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zoom 캡처",
                "verbose_name_plural": "Zoom 캡처 목록",
                "db_table": "zoom_captures",
                "ordering": ["-capture_timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="zoomsession",
            index=models.Index(
                fields=["user", "-start_time"], name="zoom_sessio_user_id_a7dfc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zoomsession",
            index=models.Index(
                fields=["session_status"], name="zoom_sessio_session_ae35db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zoomcapture",
            index=models.Index(
                fields=["session", "-capture_timestamp"],
                name="zoom_captur_session_391db4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="zoomcapture",
            index=models.Index(
                fields=["alert_triggered"], name="zoom_captur_alert_t_8931f6_idx"
            ),
        ),
    ]
