# Generated by Django 5.1 on 2025-10-31 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="이메일"
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=255, verbose_name="비밀번호 해시"),
                ),
                ("nickname", models.CharField(max_length=100, verbose_name="닉네임")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 로그인"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="관리자 여부"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                ("setting_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "notification_enabled",
                    models.BooleanField(default=True, verbose_name="알림 활성화"),
                ),
                (
                    "vibration_enabled",
                    models.BooleanField(default=True, verbose_name="진동 활성화"),
                ),
                (
                    "auto_delete_records_days",
                    models.IntegerField(default=30, verbose_name="자동 삭제 기간(일)"),
                ),
                (
                    "analysis_quality",
                    models.CharField(
                        choices=[("low", "낮음"), ("medium", "보통"), ("high", "높음")],
                        default="medium",
                        max_length=20,
                        verbose_name="분석 품질",
                    ),
                ),
                (
                    "zoom_capture_interval",
                    models.IntegerField(default=5, verbose_name="Zoom 캡처 간격(초)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "앱 설정",
                "verbose_name_plural": "앱 설정 목록",
                "db_table": "app_settings",
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "permission_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "gallery_access",
                    models.BooleanField(default=False, verbose_name="갤러리 접근"),
                ),
                (
                    "camera_access",
                    models.BooleanField(default=False, verbose_name="카메라 접근"),
                ),
                (
                    "notification_access",
                    models.BooleanField(default=False, verbose_name="알림 접근"),
                ),
                (
                    "network_access",
                    models.BooleanField(default=True, verbose_name="네트워크 접근"),
                ),
                (
                    "overlay_access",
                    models.BooleanField(default=False, verbose_name="오버레이 접근"),
                ),
                (
                    "screen_capture_access",
                    models.BooleanField(default=False, verbose_name="화면 캡처 접근"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 권한",
                "verbose_name_plural": "사용자 권한 목록",
                "db_table": "user_permissions",
            },
        ),
    ]
