# Generated by Django 5.1 on 2025-10-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisRecord",
            fields=[
                ("record_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("image", "이미지"),
                            ("video", "영상"),
                            ("screenshot", "스크린샷"),
                            ("zoom", "Zoom 캡처"),
                        ],
                        max_length=20,
                        verbose_name="분석 유형",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="파일명")),
                ("file_size", models.BigIntegerField(verbose_name="파일 크기(bytes)")),
                (
                    "file_format",
                    models.CharField(max_length=50, verbose_name="파일 형식"),
                ),
                ("original_path", models.TextField(verbose_name="원본 경로")),
                (
                    "processed_path",
                    models.TextField(blank=True, null=True, verbose_name="처리된 경로"),
                ),
                (
                    "analysis_result",
                    models.CharField(
                        choices=[
                            ("safe", "안전"),
                            ("suspicious", "의심"),
                            ("deepfake", "딥페이크"),
                        ],
                        max_length=20,
                        verbose_name="분석 결과",
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="신뢰도 점수"
                    ),
                ),
                ("processing_time", models.IntegerField(verbose_name="처리 시간(ms)")),
                (
                    "ai_model_version",
                    models.CharField(max_length=50, verbose_name="AI 모델 버전"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "분석 기록",
                "verbose_name_plural": "분석 기록 목록",
                "db_table": "analysis_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FaceDetectionResult",
            fields=[
                (
                    "detection_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("face_count", models.IntegerField(verbose_name="얼굴 개수")),
                (
                    "face_coordinates",
                    models.JSONField(
                        help_text='각 얼굴의 바운딩 박스 좌표 [{"x": 0, "y": 0, "width": 100, "height": 100}]',
                        verbose_name="얼굴 좌표",
                    ),
                ),
                (
                    "face_quality_scores",
                    models.JSONField(
                        help_text='각 얼굴의 품질 점수 [{"face_id": 1, "quality": 0.95}]',
                        verbose_name="얼굴 품질 점수",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="감지일시"),
                ),
            ],
            options={
                "verbose_name": "얼굴 인식 결과",
                "verbose_name_plural": "얼굴 인식 결과 목록",
                "db_table": "face_detection_results",
                "ordering": ["-detected_at"],
            },
        ),
    ]
