# Generated by Django 5.1 on 2025-10-31 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("detection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddField(
            model_name="facedetectionresult",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="face_detections",
                to="detection.analysisrecord",
                verbose_name="분석 기록",
            ),
        ),
        migrations.AddIndex(
            model_name="analysisrecord",
            index=models.Index(
                fields=["-created_at"], name="analysis_re_created_f3ab94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisrecord",
            index=models.Index(
                fields=["user", "-created_at"], name="analysis_re_user_id_27a903_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisrecord",
            index=models.Index(
                fields=["analysis_result"], name="analysis_re_analysi_b40876_idx"
            ),
        ),
    ]
